---
openapi: 3.0.1
info:
  title: Account Hold Service
  description: The account hold service helps to manage and support operations that are related to the holding of funds for a product account. It also restricts the accountholder’s ability to withdraw funds.
  version: 11.0.0_PRM
servers:
  - url: https://bankinghub-cert-fiservapis.azure-api.net/premier-account-hold-service/v1
paths:
  /banking/efx/v1/acctholdservice/stophold/accountHolds:
    put:
      tags:
        - Update Account Hold
      summary: Update Account Hold.
      description: Update Account Hold API updates information of the holds placed on the account. It edits the information related to hold such as the reason for hold, amount of hold, expiration date of the hold, hold type and so on
      operationId: AcctHoldModOper
      security:
        - OAuth2ClientCredentials: []
      parameters:
        - name: EFXHeader
          in: header
          schema:
            type: string
          example: '{"OrganizationId":"999990300","TrnId":"123"}'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcctHoldModOperRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcctHoldModOperResponse'
        default:
          description: Default Response for Update Account Hold
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcctHoldModOperResponse'
      x-default-example: Premier
      x-group-name: Account Hold Service
      x-proxy-name: Update Account Hold
      x-child-product-name: Transactions
      x-core: Premier
    post:
      tags:
        - Add Account Hold
      summary: Add Account Hold.
      description: Add Account Hold API creates a hold restriction on an accountholders ability to transfer or withdraw held funds from their account
      operationId: AcctHoldAddOper
      security:
        - OAuth2ClientCredentials: []
      parameters:
        - name: EFXHeader
          in: header
          schema:
            type: string
          example: '{"OrganizationId":"999990300","TrnId":"123"}'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcctHoldAddOperRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcctHoldAddOperResponse'
        default:
          description: Default Response for Add Account Hold
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcctHoldAddOperResponse'
      x-default-example: Premier
      x-group-name: Account Hold Service
      x-proxy-name: Add Account Hold
      x-child-product-name: Transactions
      x-core: Premier
  /banking/efx/v1/acctholdservice/stophold/accountHolds/secured:
    put:
      tags:
        - Delete Account Hold
      summary: Delete Account Hold.
      description: Delete Account Hold API deletes a hold (restriction) on the account so that the accountholder can transfer or withdraw held funds from their account
      operationId: AcctHoldDelBySecuredPath
      security:
        - OAuth2ClientCredentials: []
      parameters:
        - name: EFXHeader
          in: header
          schema:
            type: string
          example: '{"OrganizationId":"999990300","TrnId":"123"}'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcctHoldDelBySecuredPathRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcctHoldDelBySecuredPathResponse'
        default:
          description: Default Response for Delete Account Hold
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcctHoldDelBySecuredPathResponse'
      x-default-example: Premier
      x-group-name: Account Hold Service
      x-proxy-name: Delete Account Hold
      x-child-product-name: Transactions
      x-core: Premier
    post:
      tags:
        - Get Account Hold
      summary: Get Account Hold.
      description: Get Account Hold API retrieves the list of holds (restrictions) placed on the account. This API can be used to retrieve details of one specific hold (restriction) if hold identifier is provided.
      operationId: AcctHoldInqBySecuredPath
      security:
        - OAuth2ClientCredentials: []
      parameters:
        - name: EFXHeader
          in: header
          schema:
            type: string
          example: '{"OrganizationId":"999990300","TrnId":"123"}'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcctHoldInqBySecuredPathRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcctHoldInqBySecuredPathResponse'
        default:
          description: Default Response for Get Account Hold
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcctHoldInqBySecuredPathResponse'
      x-default-example: Premier
      x-group-name: Account Hold Service
      x-proxy-name: Get Account Hold
      x-child-product-name: Transactions
      x-core: Premier
components:
  securitySchemes:
    OAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://bankinghub-cert-fiservapis.azure-api.net/premier-account-hold-service/v1/fts-apim/oauth2/v2
          scopes:
            type: string
            example: ok
  schemas:
    AcctHoldAddOperRequest:
      type: object
      required:
        - AcctHoldInfo
      properties:
        OvrdAutoAckInd:
          type: boolean
          example: true
        AcctHoldInfo:
          $ref: '#/components/schemas/AcctHoldAddOperRequest_AcctHoldInfo'
    AcctHoldAddOperResponse:
      required:
        - AcctHoldStatusRec
      properties:
        Status:
          $ref: '#/components/schemas/StatusType'
        AcctHoldStatusRec:
          $ref: '#/components/schemas/AcctHoldAddOperResponse_AcctHoldStatusRec'
      example:
        Status:
          StatusCode: '0'
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Premier
        AcctHoldStatusRec:
          AcctHoldKeys:
            AcctKeys:
              AcctId: '10614'
              AcctType: DDA
            AcctHoldIdent: '1'
          AcctHoldStatus:
            AcctHoldStatusCode: Valid
            EffDt: '2023-06-16T19:48:46.500'
    AcctHoldDelBySecuredPathRequest:
      type: object
      required:
        - AcctHoldKeys
      properties:
        AcctHoldKeys:
          $ref: '#/components/schemas/AcctHoldDelBySecuredPathRequest_AcctHoldKeys'
    AcctHoldDelBySecuredPathResponse:
      required:
        - AcctHoldStatusRec
      properties:
        Status:
          $ref: '#/components/schemas/StatusType'
        AcctHoldStatusRec:
          $ref: '#/components/schemas/AcctHoldDelBySecuredPathResponse_AcctHoldStatusRec'
      example:
        Status:
          StatusCode: '0'
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Premier
        AcctHoldStatusRec:
          AcctHoldKeys:
            AcctKeys:
              AcctId: '10614'
              AcctType: DDA
            AcctHoldIdent: '2'
          AcctHoldStatus:
            AcctHoldStatusCode: Deleted
            EffDt: '2023-06-16T19:55:31.241'
    AcctHoldInqBySecuredPathRequest:
      type: object
      properties:
        AcctHoldSel:
          $ref: '#/components/schemas/AcctHoldInqBySecuredPathRequest_AcctHoldSel'
    AcctHoldInqBySecuredPathResponse:
      required:
        - AcctHoldRec
      properties:
        Status:
          $ref: '#/components/schemas/StatusType'
        RecCtrlOut:
          $ref: '#/components/schemas/AcctHoldInqBySecuredPathResponse_RecCtrlOut'
        AcctHoldRec:
          type: array
          description: Details of the account hold response record that includes response keys, response status and response information.
          items:
            $ref: '#/components/schemas/AcctHoldInqBySecuredPathResponse_AcctHoldRec'
      example:
        Status:
          StatusCode: '0'
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Premier
        RecCtrlOut:
          SentRecCount: 1
        AcctHoldRec:
          - AcctHoldKeys:
              AcctKeys:
                AcctId: '5041733'
                AcctType: DDA
              AcctHoldIdent: '1'
            AcctHoldInfo:
              CurAmt:
                Amt: 50
                CurCode:
                  CurCodeType: ISO4217-Alpha
                  CurCodeValue: USD
              RelationshipMgr:
                - RelationshipMgrIdent: '350'
                  RelationshipRole: Officer
              ReportGroupCode: '123'
              SecuredAcctRef:
                AcctKeys:
                  AcctId: '1082108810'
                  AcctType: LOAN
              MaxPledgeAmt:
                Amt: 50
                CurCode:
                  CurCodeType: ISO4217-Alpha
                  CurCodeValue: USD
              HoldReason:
                - Billing address info is not valid
              ExpDt: '2026-12-12'
              EffDt: '2018-03-01T00:04:31.590'
              AcctHoldOption: FixedAmt
              AcctHoldIdent: '1'
              PendingHoldAmt:
                Amt: 100
                CurCode:
                  CurCodeType: ISO4217-Alpha
                  CurCodeValue: USD
            AcctHoldStatus:
              AcctHoldStatusCode: Valid
              EffDt: '2023-06-16T19:48:14.532'
    AcctHoldModOperRequest:
      type: object
      required:
        - AcctHoldInfo
        - AcctHoldKeys
      properties:
        AcctHoldKeys:
          $ref: '#/components/schemas/AcctHoldModOperRequest_AcctHoldKeys'
        AcctHoldInfo:
          $ref: '#/components/schemas/AcctHoldModOperRequest_AcctHoldInfo'
    AcctHoldModOperResponse:
      required:
        - AcctHoldStatusRec
      properties:
        Status:
          $ref: '#/components/schemas/StatusType'
        AcctHoldStatusRec:
          $ref: '#/components/schemas/AcctHoldModOperResponse_AcctHoldStatusRec'
      example:
        Status:
          StatusCode: '0'
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Premier
        AcctHoldStatusRec:
          AcctHoldKeys:
            AcctKeys:
              AcctId: '10614'
              AcctType: DDA
            AcctHoldIdent: '2'
          AcctHoldStatus:
            AcctHoldStatusCode: Valid
            EffDt: '2023-06-16T19:52:05.235'
    StatusType:
      title: StatusType
      required:
        - Severity
        - StatusCode
        - StatusDesc
        - SvcProviderName
      type: object
      properties:
        Id:
          type: string
          description: Status identification number.
        StatusCode:
          maxLength: 20
          type: string
          description: EFX Standard Status code that indicates the result of API response. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section to view the list of all possible status codes.
        StatusDesc:
          maxLength: 255
          type: string
          description: Brief information about the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section for more information.
        Severity:
          $ref: '#/components/schemas/SeverityType'
        SvcProviderName:
          maxLength: 1024
          type: string
          description: |-
            Name of a service provider. Possible values are:
              -  Cleartouch
              -  DNA
              -  Precision
              -  Premier
              -  Signature
        ServerStatusCode:
          maxLength: 20
          type: string
          description: Server status code of the service provider's application.
        ServerStatusDesc:
          maxLength: 255
          type: string
          description: Description of the server status code of the service provider's application.
        OvrdExceptionInd:
          type: boolean
          description: Flag to indicate whether the exception can be overridden by resubmitting the request message.
        SubjectRole:
          type: string
          description: Authorization level required to override, such as Teller and Supervisor.
        SubjectElement:
          type: array
          description: Information about the elements that caused the status.
          items:
            $ref: '#/components/schemas/SubjectElementType'
        ContentHTML:
          type: string
          description: Response status in HTML format. This parameter returns only in some cases.
        AdditionalStatus:
          type: array
          description: Details of the additional status of the response message. This aggregate can appear once for each additional status that the server is expected to provide.
          items:
            $ref: '#/components/schemas/AdditionalStatusType'
      description: Details of the API response messages.
    SeverityType:
      title: SeverityType
      type: string
      description: Severity type of the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section for more information.
      enum:
        - Error
        - Warning
        - Info
    SubjectElementType:
      title: SubjectElementType
      type: object
      properties:
        Path:
          type: string
          description: Path of the element (in XPath absolute notation format) where the error occurred.  If the error occurred at the top-level element, then name of the element is returned in the response.
        ServerPath:
          maxLength: 256
          type: string
          description: Server Path is the Service Provider’s identification of the field in their schema, such as an XPath, field ID, or field name that is associated with the ServerStatusCode. If this element is set, it must be returned in the ServerPath element of the OvrdExceptionData aggregate if the exception is being overridden.
        Value:
          maxLength: 256
          type: string
          description: Human readable information of the EFX data value of the element to be overridden. This value should not be provided for the fields that cannot be represented as a string, for example, binary data.
      description: Information about the subject element
    AdditionalStatusType:
      title: AdditionalStatusType
      type: object
      properties:
        StatusCode:
          maxLength: 20
          type: string
          description: EFX Standard Status code that indicates the result of API response. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section to view the list of all possible status codes.
        StatusDesc:
          maxLength: 255
          type: string
          description: Brief information about the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> for more information.
        Severity:
          $ref: '#/components/schemas/SeverityType'
        SvcProviderName:
          maxLength: 1024
          type: string
          description: |-
            Name of a service provider. Possible values are:
              - Cleartouch
              - DNA
              - Precision
              - Premier
              - Signature
        ServerStatusCode:
          maxLength: 20
          type: string
          description: "Server status code of the service provider's application.  "
        ServerStatusDesc:
          maxLength: 255
          type: string
          description: Description of the server status code of the service provider's application.
        OvrdExceptionInd:
          type: boolean
          description: Flag that indicates whether the exception can be overridden by resubmitting the request message.
        SubjectElement:
          type: array
          description: Information about the elements that caused the status.
          items:
            $ref: '#/components/schemas/SubjectElementType'
    AcctHoldAddOperRequest_AcctHoldInfo_AcctRef_AcctKeys:
      required:
        - AcctId
      type: object
      properties:
        AcctId:
          maxLength: 36
          type: string
          example: '10615'
          description: |+
            Unique identification number of an account record.
        AcctType:
          type: string
          description: |-
            Type of an account.
          enum:
            - CDA
            - DDA
            - SDA
          example: 'DDA'
      description: Unique information to identify the account record.
    AcctHoldAddOperRequest_AcctHoldInfo_AcctRef:
      required:
        - AcctKeys
      type: object
      properties:
        AcctKeys:
          $ref: '#/components/schemas/AcctHoldAddOperRequest_AcctHoldInfo_AcctRef_AcctKeys'
      description: Reference information of an account object on which a hold is placed.
    AcctHoldAddOperRequest_AcctHoldInfo_CurAmt_CurCode:
      required:
        - CurCodeValue
      type: object
      properties:
        CurCodeType:
          type: string
          description: Standard ISO currency code format.
          enum:
            - ISO4217-Alpha
            - ISO_4217_ALPHA
          example: 'ISO_4217_ALPHA'
        CurCodeValue:
          type: string
          example: 'USD'
          description: "Currency code value as per the ISO currency code format set in the CurCodeType field.\n\n\n\nFor example, currency code for the US dollar in alpha and numeric formats are:\n\n\n\n- USD (in ISO4217-Alpha format) \n\n\n\n- 840 (in ISO4217-Numeric format)\n\n\n\n\n\n\n\nPlease note that presently only USD currency code is supported."
      description: |+
        Details of the currency code.
    AcctHoldAddOperRequest_AcctHoldInfo_CurAmt:
      type: object
      properties:
        Amt:
          type: number
          format: float
          example: 1000.00
          description: |-
            Amount in decimal format.
            Example: 10.00
            **Note:** If account is pledged a collateral for a loan, as such a loan account is specified, then Premier will be calculating the amount. Therefore the hold amount is not expected.
        CurCode:
          $ref: '#/components/schemas/AcctHoldAddOperRequest_AcctHoldInfo_CurAmt_CurCode'
      description: Details of the amount to be processed.
    AcctHoldAddOperRequest_AcctHoldInfo_RelationshipMgr:
      required:
        - RelationshipMgrIdent
      properties:
        RelationshipMgrIdent:
          maxLength: 36
          type: string
          description: Unique identifier of a relationship manager.
        RelationshipRole:
          type: string
          description: Role of a relationship manager.
          enum:
            - Officer
    AcctHoldAddOperRequest_AcctHoldInfo_SecuredAcctRef_AcctKeys:
      required:
        - AcctId
      type: object
      properties:
        AcctId:
          maxLength: 36
          type: string
          example: '1082108810'
          description: |-
            Unique account identification number.
            **Note:** Loan account number to which the account is pledged.
        AcctType:
          type: string
          example: 'LOAN'
          description: |-
            Type of an account.
          enum:
            - LOAN
      description: Unique information to identify the account record.
    AcctHoldAddOperRequest_AcctHoldInfo_SecuredAcctRef:
      required:
        - AcctKeys
      type: object
      properties:
        AcctKeys:
          $ref: '#/components/schemas/AcctHoldAddOperRequest_AcctHoldInfo_SecuredAcctRef_AcctKeys'
      description: Reference details of the secured account.
    AcctHoldAddOperRequest_AcctHoldInfo_MaxPledgeAmt_CurCode:
      required:
        - CurCodeValue
      type: object
      properties:
        CurCodeType:
          type: string
          description: Standard ISO currency code format.
          enum:
            - ISO4217-Alpha
            - ISO_4217_ALPHA
          example: 'ISO_4217_ALPHA'
        CurCodeValue:
          type: string
          example: 'USD'
          description: |-
            Currency code value as per the ISO4217-Alpha format.
            Please note that presently only USD currency code is supported.
      description: |+
        Currency code applicable for an account.
    AcctHoldAddOperRequest_AcctHoldInfo_MaxPledgeAmt:
      type: object
      properties:
        Amt:
          type: number
          format: float
          example: 50.0
          description: |-
            Amount in decimal format.
            Example: 10.00
        CurCode:
          $ref: '#/components/schemas/AcctHoldAddOperRequest_AcctHoldInfo_MaxPledgeAmt_CurCode'
      description: Amount of funds in an account that can be used as collateral.
    AcctHoldAddOperRequest_AcctHoldInfo_PendingHoldAmt:
      type: object
      properties:
        Amt:
          type: number
          format: float
          example: 100.0
          description: Value of pending amount.
        CurCode:
          $ref: '#/components/schemas/AcctHoldAddOperRequest_AcctHoldInfo_MaxPledgeAmt_CurCode'
      description: Details of hold amount that will be placed on an account.
    AcctHoldAddOperRequest_AcctHoldInfo:
      type: object
      properties:
        AcctHoldOption:
          type: string
          description: |-
            Refers to the option used to calculate the hold amount.

            **Note:** If specifying a loan or a hold amount, then premier expects the account hold option to be a fixed. If hold amount is not specified and the account does not use collateral for the loan, then either the available balance or ledger balance of the account can be used.
          enum:
            - FixedAmt
            - AvailBal
            - LedgerBal
          example: 'FixedAmt'
        AcctRef:
          $ref: '#/components/schemas/AcctHoldAddOperRequest_AcctHoldInfo_AcctRef'
        CurAmt:
          $ref: '#/components/schemas/AcctHoldAddOperRequest_AcctHoldInfo_CurAmt'
        DelayHoldInd:
          type: boolean
          example: true
        ExpDt:
          type: string
          description: "Date after which the hold on an account is no longer active and the funds are made available.\n\n\n\nFormat: yyyy-mm-dd \n\n\n\nExample: 2021-11-20"
          format: date
          example: '2026-12-12'
        EffDt:
          pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?'
          type: string
          example: '2018-03-01'
          description: |-
            Effective date and time when the hold on an account becomes active.
            Format: yyyy-MM-ddTHH:mm:ss.sss
            Example: 2021-06-28T23:40:30.888
            Future date is not supported in this field.
            **Note:** Effective date can be accepted as a current date and back date.
            It should always be before the expiration date.
        HoldReason:
          type: array
          description: Reason for placing the hold on an account.
          items:
            type: string
          example:
            - Billing address info is not valid
        MaxPledgeAmt:
          $ref: '#/components/schemas/AcctHoldAddOperRequest_AcctHoldInfo_MaxPledgeAmt'
        Memo:
          type: string
          example: 'Account Hold'
        PendingHoldAmt:
          $ref: '#/components/schemas/AcctHoldAddOperRequest_AcctHoldInfo_PendingHoldAmt'
        RelationshipMgr:
          type: array
          description: Information about the financial institution officers who have management-related responsibilities of the account.
          items:
            $ref: '#/components/schemas/AcctHoldAddOperRequest_AcctHoldInfo_RelationshipMgr'
          example:
            - RelationshipMgrIdent: '350'
              RelationshipRole: 'OFFICER'
        ReportGroupCode:
          type: string
          example: '123'
          description: Client-defined code to group the accounts for reporting purposes.
        RestrictedInd:
          type: string
          example: true
        SecuredAcctRef:
          $ref: '#/components/schemas/AcctHoldAddOperRequest_AcctHoldInfo_SecuredAcctRef'
        WaiveFeeInd:
          type: boolean
          example: true
      description: Information about the business properties of the hold placed on an account.
    AcctHoldAddOperResponse_AcctHoldStatusRec_AcctHoldKeys_AcctKeys:
      required:
        - AcctId
      type: object
      properties:
        AcctId:
          maxLength: 36
          type: string
          description: Unique identifier of an account record.
        AcctType:
          type: string
          description: |-
            Type of an account.
          enum:
            - DDA
            - CDA
            - SDA
      description: Unique information to identify the account record.
    AcctHoldAddOperResponse_AcctHoldStatusRec_AcctHoldKeys:
      required:
        - AcctKeys
      type: object
      properties:
        AcctKeys:
          $ref: '#/components/schemas/AcctHoldAddOperResponse_AcctHoldStatusRec_AcctHoldKeys_AcctKeys'
        AcctHoldIdent:
          maxLength: 36
          type: string
          description: Unique identification number used to identify the hold record.
      description: 'Unique information to identify the account hold record. '
    AcctHoldAddOperResponse_AcctHoldStatusRec_AcctHoldStatus:
      required:
        - AcctHoldStatusCode
      type: object
      properties:
        AcctHoldStatusCode:
          type: string
          description: Code to indicate the current status of the account hold.
          enum:
            - Valid
        EffDt:
          pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?'
          type: string
          description: |-
            Effective date and time when the status of the account hold is changed.
            Format: yyyy-MM-ddTHH:mm:ss.sss
            Example: 2021-06-28T23:40:30.888
      description: Details of the account hold status.
    AcctHoldAddOperResponse_AcctHoldStatusRec:
      required:
        - AcctHoldKeys
        - AcctHoldStatus
      type: object
      properties:
        AcctHoldKeys:
          $ref: '#/components/schemas/AcctHoldAddOperResponse_AcctHoldStatusRec_AcctHoldKeys'
        AcctHoldStatus:
          $ref: '#/components/schemas/AcctHoldAddOperResponse_AcctHoldStatusRec_AcctHoldStatus'
      description: Details of the account hold response record that includes response keys and response status.
    AcctHoldDelBySecuredPathRequest_AcctHoldKeys_AcctKeys:
      required:
        - AcctId
      type: object
      properties:
        AcctId:
          maxLength: 36
          type: string
          example: '10615'
          description: Unique account identification number.
        AcctType:
          type: string
          description: |-
            Type of an account.
          enum:
            - CDA
            - DDA
            - SDA
          example: 'DDA'
      description: Unique information to identify the account record.
    AcctHoldDelBySecuredPathRequest_AcctHoldKeys:
      required:
        - AcctKeys
      type: object
      properties:
        AcctKeys:
          $ref: '#/components/schemas/AcctHoldDelBySecuredPathRequest_AcctHoldKeys_AcctKeys'
        AcctHoldIdent:
          maxLength: 36
          type: string
          example: '2'
          description: Identification number used to identify the hold record.
      description: 'Unique information to identify the account hold record. '
    AcctHoldDelBySecuredPathResponse_AcctHoldStatusRec_AcctHoldKeys_AcctKeys:
      required:
        - AcctId
      type: object
      properties:
        AcctId:
          maxLength: 36
          type: string
          description: Unique identifier of an account record.
        AcctType:
          type: string
          description: |-
            Type of an account.
          enum:
            - CDA
            - DDA
            - SDA
      description: Unique information to identify the account record.
    AcctHoldDelBySecuredPathResponse_AcctHoldStatusRec_AcctHoldKeys:
      required:
        - AcctKeys
      type: object
      properties:
        AcctKeys:
          $ref: '#/components/schemas/AcctHoldDelBySecuredPathResponse_AcctHoldStatusRec_AcctHoldKeys_AcctKeys'
        AcctHoldIdent:
          maxLength: 36
          type: string
          description: Identification number used to identify the hold record.
      description: 'Unique information to identify the account hold record. '
    AcctHoldDelBySecuredPathResponse_AcctHoldStatusRec_AcctHoldStatus:
      required:
        - AcctHoldStatusCode
      type: object
      properties:
        AcctHoldStatusCode:
          type: string
          description: Code to indicate the current status of the account hold.
          enum:
            - Deleted
        EffDt:
          pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?'
          type: string
          description: |-
            Effective date and time when the status of the account hold is changed.
            Format: yyyy-MM-ddTHH:mm:ss.sss
            Example: 2021-06-28T23:40:30.888
      description: Details of the account hold status.
    AcctHoldDelBySecuredPathResponse_AcctHoldStatusRec:
      required:
        - AcctHoldKeys
        - AcctHoldStatus
      type: object
      properties:
        AcctHoldKeys:
          $ref: '#/components/schemas/AcctHoldDelBySecuredPathResponse_AcctHoldStatusRec_AcctHoldKeys'
        AcctHoldStatus:
          $ref: '#/components/schemas/AcctHoldDelBySecuredPathResponse_AcctHoldStatusRec_AcctHoldStatus'
      description: Details of the account hold response record that includes response keys and response status.
    AcctHoldInqBySecuredPathRequest_AcctHoldSel_AcctHoldKeys:
      required:
        - AcctKeys
      type: object
      properties:
        AcctKeys:
          $ref: '#/components/schemas/AcctHoldDelBySecuredPathRequest_AcctHoldKeys_AcctKeys'
        AcctHoldIdent:
          maxLength: 36
          type: string
          example: '2'
          description: |+
            Identification number used to identify the hold record.
            **Note:** Refers to the hold addenda number.
      description: Details of the account keys used to identify a specific hold record.
    AcctHoldInqBySecuredPathRequest_AcctHoldSel:
      type: object
      properties:
        AcctHoldKeys:
          type: array
          items:
            $ref: '#/components/schemas/AcctHoldInqBySecuredPathRequest_AcctHoldSel_AcctHoldKeys'
      description: Details of the selection criteria used to identify holds placed on an account.
    AcctHoldInqBySecuredPathResponse_RecCtrlOut:
      required:
        - SentRecCount
      type: object
      properties:
        SentRecCount:
          type: integer
          description: |-
            Total number of hold records included in the response that matched the selection criteria for an account.
            **Note:** Premier supports up to 99 hold records.
          format: int64
      description: |+
        Detailed information used to retrieve the records that are matching client specified selection criteria.
        **Note:** Applicable if client uses the ReccCtrlIn aggregate in the request.
    AcctHoldInqBySecuredPathResponse_AcctHoldKeys:
      required:
        - AcctKeys
      type: object
      properties:
        AcctKeys:
          $ref: '#/components/schemas/AcctHoldDelBySecuredPathRequest_AcctHoldKeys_AcctKeys'
        AcctHoldIdent:
          maxLength: 36
          type: string
          description: Identification of the hold record.
      description: Unique information to identify the account hold record.
    AcctHoldInqBySecuredPathResponse_AcctHoldInfo_CurAmt_CurCode:
      required:
        - CurCodeValue
      type: object
      properties:
        CurCodeType:
          type: string
          description: "Standard ISO currency code format. \n\n\n\n\n\n\n\nRefer to the <a href=\"https://en.wikipedia.org/wiki/ISO_4217\">ISO 4217 codes </a> to view the list of all currency codes."
          enum:
            - ISO4217-Alpha
        CurCodeValue:
          type: string
          description: "Currency code value as per the ISO currency code format set in the CurCodeType field.\n\nFor example, currency code for the US Dollar in alpha and numeric formats are:\n\n- USD (in ISO4217-Alpha format) \n\n- 840 (in ISO4217-Numeric format)\n\n\n\n **Note:** Only USD currency code is supported."
      description: |+
        Details of currency code.

    AcctHoldInqBySecuredPathResponse_AcctHoldInfo_CurAmt:
      type: object
      properties:
        Amt:
          type: number
          description: |-
            Amount in decimal format.
            Example: 10.00
        CurCode:
          $ref: '#/components/schemas/AcctHoldInqBySecuredPathResponse_AcctHoldInfo_CurAmt_CurCode'
      description: Amount of the hold placed on the account.
    AcctHoldInqBySecuredPathResponse_AcctHoldInfo_RelationshipMgr:
      required:
        - RelationshipMgrIdent
      properties:
        RelationshipMgrIdent:
          maxLength: 36
          type: string
          description: Client-defined responsibility code to identify the officer responsible for the account.
        RelationshipRole:
          type: string
          description: |+
            Role of a relationship manager.
          enum:
            - Officer
    AcctHoldInqBySecuredPathResponse_AcctHoldInfo_SecuredAcctRef_AcctKeys:
      required:
        - AcctId
      type: object
      properties:
        AcctId:
          maxLength: 36
          type: string
          description: |-
            Unique account identification number.
            **Note:** Refers to the loan account number to which the account is pledged.
        AcctType:
          type: string
          description: |-
            Type of an account.
          enum:
            - LOAN
      description: Unique information to identify the account record.
    AcctHoldInqBySecuredPathResponse_AcctHoldInfo_SecuredAcctRef:
      required:
        - AcctKeys
      type: object
      properties:
        AcctKeys:
          $ref: '#/components/schemas/AcctHoldInqBySecuredPathResponse_AcctHoldInfo_SecuredAcctRef_AcctKeys'
      description: Reference details of an account against which the securities have been submitted by account-holder as collateral.
    AcctHoldInqBySecuredPathResponse_AcctHoldInfo_MaxPledgeAmt_CurCode:
      required:
        - CurCodeValue
      type: object
      properties:
        CurCodeType:
          type: string
          description: "Standard ISO currency code format. \n\n\n\nRefer to the <a href=\"https://en.wikipedia.org/wiki/ISO_4217\">ISO 4217 codes </a> to view the list of all currency codes."
          enum:
            - ISO4217-Alpha
        CurCodeValue:
          type: string
          description: "Currency code value as per the ISO currency code format set in the CurCodeType field.\n\nFor example, currency code for the US Dollar in alpha and numeric formats are:\n\n- USD (in ISO4217-Alpha format) \n\n- 840 (in ISO4217-Numeric format)\n\n\n\n **Note:** Only USD currency code is supported."
      description: |+
        Currency code applicable for an account.
    AcctHoldInqBySecuredPathResponse_AcctHoldInfo_MaxPledgeAmt:
      type: object
      properties:
        Amt:
          type: number
          description: |-
            Amount value submitted as collateral in decimal format.
            Example: 10.00
        CurCode:
          $ref: '#/components/schemas/AcctHoldInqBySecuredPathResponse_AcctHoldInfo_MaxPledgeAmt_CurCode'
      description: Amount of funds in the account that can be used as collateral.
    AcctHoldInqBySecuredPathResponse_AcctHoldInfo_PendingHoldAmt:
      type: object
      properties:
        Amt:
          type: number
          description: |-
            Amount in decimal format.
            Example: 10.00
        CurCode:
          $ref: '#/components/schemas/AcctHoldInqBySecuredPathResponse_AcctHoldInfo_MaxPledgeAmt_CurCode'
      description: Details of hold amount that will be placed on an account.
    AcctHoldInqBySecuredPathResponse_AcctHoldInfo:
      type: object
      properties:
        CurAmt:
          $ref: '#/components/schemas/AcctHoldInqBySecuredPathResponse_AcctHoldInfo_CurAmt'
        RelationshipMgr:
          type: array
          description: Information about officers who have management-related responsibilities of an account.
          items:
            $ref: '#/components/schemas/AcctHoldInqBySecuredPathResponse_AcctHoldInfo_RelationshipMgr'
        ReportGroupCode:
          type: string
          description: Client-defined code to group accounts for reporting purpose.
        SecuredAcctRef:
          $ref: '#/components/schemas/AcctHoldInqBySecuredPathResponse_AcctHoldInfo_SecuredAcctRef'
        MaxPledgeAmt:
          $ref: '#/components/schemas/AcctHoldInqBySecuredPathResponse_AcctHoldInfo_MaxPledgeAmt'
        HoldReason:
          type: array
          description: |+
            Description of the reason for placing the hold on an account.

          items: {}
        ExpDt:
          type: string
          description: "Date after which the hold on an account is no longer active and the funds are made available.\n\n\n\nFormat: yyyy-mm-dd \n\n\n\nExample: 2021-11-20"
          format: date
        EffDt:
          pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?'
          type: string
          description: |-
            Effective date and time value when the hold on an account will be active.
            Format: {yyyy-MM-ddTHH:mm:ss.sss}
            Example: 2021-06-28T23:40:30.888
        AcctHoldOption:
          type: string
          description: |+
            Indicates the type of hold to be placed on an account and depending on this the hold amount calculation is done.
          enum:
            - FixedAmt
            - AvailBal
            - LedgerBal
        AcctHoldIdent:
          maxLength: 36
          type: string
          description: Identification of the hold addenda.
        PendingHoldAmt:
          $ref: '#/components/schemas/AcctHoldInqBySecuredPathResponse_AcctHoldInfo_PendingHoldAmt'
        PendingHoldDt:
          type: string
          description: |-
            Date at which hold will become effective.
            Format: yyyy-mm-dd
            Example: 2021-11-20
          format: date
      description: Properties of an account that has been put on hold and details of restrictions imposed.
    AcctHoldInqBySecuredPathResponse_AcctHoldRec:
      required:
        - AcctHoldInfo
        - AcctHoldKeys
        - AcctHoldStatus
      properties:
        AcctHoldKeys:
          $ref: '#/components/schemas/AcctHoldInqBySecuredPathResponse_AcctHoldKeys'
        AcctHoldInfo:
          $ref: '#/components/schemas/AcctHoldInqBySecuredPathResponse_AcctHoldInfo'
        AcctHoldStatus:
          $ref: '#/components/schemas/AcctHoldAddOperResponse_AcctHoldStatusRec_AcctHoldStatus'
    AcctHoldModOperRequest_AcctHoldKeys_AcctKeys:
      required:
        - AcctId
      type: object
      properties:
        AcctId:
          maxLength: 36
          type: string
          example: '10615'
          description: Unique identification number of an account record.
        AcctType:
          type: string
          example: 'DDA'
          description: |-
            Type of an account.
          enum:
            - DDA
            - SDA
            - CDA
      description: Unique information to identify the account record.
    AcctHoldModOperRequest_AcctHoldKeys:
      required:
        - AcctKeys
      type: object
      properties:
        AcctKeys:
          $ref: '#/components/schemas/AcctHoldModOperRequest_AcctHoldKeys_AcctKeys'
        HoldType:
          type: string
          example: 'Hold'
        AcctHoldIdent:
          maxLength: 36
          type: string
          example: '2'
          description: |-
            Identification number used to identify the hold record.
            **Note:** *Required filed*
      description: Unique information to identify the account hold record.
    AcctHoldModOperRequest_AcctHoldInfo_CurAmt_CurCode:
      required:
        - CurCodeValue
      type: object
      properties:
        CurCodeType:
          type: string
          description: Standard ISO currency code format.
          enum:
            - ISO4217-Alpha
          example: 'ISO4217-Alpha'
        CurCodeValue:
          type: string
          example: 'USD'
          description: "Currency code value as per the ISO currency code format set in the CurCodeType field.\n\nFor example, currency code for the US Dollar in alpha and numeric formats are:\n\n- USD (in ISO4217-Alpha format) \n\n- 840 (in ISO4217-Numeric format)\n\n\n\n **Note:** Only USD currency code is supported."
      description: |+
        Details of the currency code.
    AcctHoldModOperRequest_AcctHoldInfo_CurAmt:
      type: object
      properties:
        Amt:
          type: number
          format: float
          example: 10.01
          description: |-
            Amount in decimal format.
            Example: 10.00
            **Note:** If account is pledged as a collateral for a loan and a loan account is specified then premier calculates the amount and the hold amount is not expected.
        CurCode:
          $ref: '#/components/schemas/AcctHoldModOperRequest_AcctHoldInfo_CurAmt_CurCode'
      description: Details of the amount to be processed.
    AcctHoldModOperRequest_AcctHoldInfo:
      type: object
      properties:
        HoldType:
          type: string
          example: 'Hold'
        CurAmt:
          $ref: '#/components/schemas/AcctHoldModOperRequest_AcctHoldInfo_CurAmt'
        HoldReason:
          type: array
          description: Reason for placing the hold on an account.
          items:
            type: string
          example:
            - Modified Account Hold Amount
        ExpDt:
          type: string
          example: '2025-10-09'
          description: "Date after which the hold on an account is no longer active and the funds are made available.\n\n\n\nFormat: yyyy-mm-dd \n\nExample: 2021-11-20"
          format: date
        WaiveFeeInd:
          type: boolean
          example: true
      description: Information about the business properties of the hold placed on an account.
    AcctHoldModOperResponse_AcctHoldStatusRec_AcctHoldKeys_AcctKeys:
      required:
        - AcctId
      type: object
      properties:
        AcctId:
          maxLength: 36
          type: string
          description: Unique account identification number.
        AcctType:
          type: string
          description: |-
            Type of an account.
          enum:
            - DDA
            - CDA
            - SDA
      description: Unique information to identify the account record.
    AcctHoldModOperResponse_AcctHoldStatusRec_AcctHoldKeys:
      required:
        - AcctKeys
      type: object
      properties:
        AcctKeys:
          $ref: '#/components/schemas/AcctHoldModOperResponse_AcctHoldStatusRec_AcctHoldKeys_AcctKeys'
        AcctHoldIdent:
          maxLength: 36
          type: string
          description: Identification number used to identify the hold record.
      description: Unique information to identify the account hold record.
    AcctHoldModOperResponse_AcctHoldStatusRec:
      required:
        - AcctHoldKeys
        - AcctHoldStatus
      type: object
      properties:
        AcctHoldKeys:
          $ref: '#/components/schemas/AcctHoldModOperResponse_AcctHoldStatusRec_AcctHoldKeys'
        AcctHoldStatus:
          $ref: '#/components/schemas/AcctHoldAddOperResponse_AcctHoldStatusRec_AcctHoldStatus'
      description: Details of the account hold response record that includes response keys and response status.
