---
openapi: 3.0.1
info:
  title: Beneficiary Service
  description: Beneficiary service consists of operations used to manage the beneficial party associated with an account. Beneficial party nominated, can claim the proceeds of the bank account post the demise of account holder.
  version: 11.0.0_PRM
servers:
  - url: https://bankinghub-cert-fiservapis.azure-api.net/beneficiary-service
paths:
  /banking/efx/v1/beneficiaryservice/partyacctsvc/beneficiaries:
    put:
      tags:
        - Update Beneficiary
      summary: Update Beneficiary.
      description: Update Beneficiary API modifies beneficiary information associated to an account.
      operationId: modBeneficiary
      security:
        - OAuth2ClientCredentials: []
      parameters:
        - name: EFXHeader
          in: header
          schema:
            type: string
          example: '{"OrganizationId":"999990300","TrnId":"123"}'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modBeneficiaryRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modBeneficiaryResponse'
        default:
          description: Default Response for Update Beneficiary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modBeneficiaryResponse'
      x-group-name: Beneficiary Service
      x-proxy-name: Update Beneficiary
      x-child-product-name: Accountholder
      x-core: Premier
    post:
      tags:
        - Add Beneficiary
      summary: Add Beneficiary.
      description: Add Beneficiary API adds a beneficiary to an account.
      operationId: addBeneficiary
      security:
        - OAuth2ClientCredentials: []
      parameters:
        - name: EFXHeader
          in: header
          schema:
            type: string
          example: '{"OrganizationId":"999990300","TrnId":"123"}'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addBeneficiaryRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addBeneficiaryResponse'
        default:
          description: Default Response for Add Beneficiary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addBeneficiaryResponse'
      x-group-name: Beneficiary Service
      x-proxy-name: Add Beneficiary
      x-child-product-name: Accountholder
      x-core: Premier
  /banking/efx/v1/beneficiaryservice/partyacctsvc/beneficiaries/secured:
    put:
      tags:
        - Delete Beneficiary
      summary: Delete Beneficiary.
      description: Delete Beneficiary API deletes the beneficiary information linked to an account
      operationId: delBeneficiarySecured
      security:
        - OAuth2ClientCredentials: []
      parameters:
        - name: EFXHeader
          in: header
          schema:
            type: string
          example: '{"OrganizationId":"999990300","TrnId":"123"}'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/delBeneficiarySecuredRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/delBeneficiarySecuredResponse'
        default:
          description: Default Response for Delete Beneficiary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/delBeneficiarySecuredResponse'
      x-group-name: Beneficiary Service
      x-proxy-name: Delete Beneficiary
      x-child-product-name: Accountholder
      x-core: Premier
    post:
      tags:
        - Get Beneficiary
      summary: Get Beneficiary.
      description: Get Beneficiary API retrieves the list and information of the beneficiary associated with an account
      operationId: getBeneficiary
      security:
        - OAuth2ClientCredentials: []
      parameters:
        - name: EFXHeader
          in: header
          schema:
            type: string
          example: '{"OrganizationId":"999990300","TrnId":"123"}'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getBeneficiaryRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getBeneficiaryResponse'
        default:
          description: Default Response for Get Beneficiary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getBeneficiaryResponse'
      x-group-name: Beneficiary Service
      x-proxy-name: Get Beneficiary
      x-child-product-name: Accountholder
      x-core: Premier
components:
  securitySchemes:
    OAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://bankinghub-cert-fiservapis.azure-api.net/beneficiary-service/fts-apim/oauth2/v2
          scopes:
            type: string
            example: ok
  schemas:
    addBeneficiaryRequest:
      type: object
      required:
        - BeneficiaryInfo
      properties:
        BeneficiaryInfo:
          $ref: '#/components/schemas/addBeneficiaryRequest_BeneficiaryInfo'
    StatusType:
      title: StatusType
      required:
        - Severity
        - StatusCode
        - StatusDesc
        - SvcProviderName
      type: object
      properties:
        Id:
          type: string
          description: Status identification number.
        StatusCode:
          maxLength: 20
          type: string
          description: EFX Standard Status code that indicates the result of API response. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section to view the list of all possible status codes.
        StatusDesc:
          maxLength: 255
          type: string
          description: Brief information about the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section for more information.
        Severity:
          $ref: '#/components/schemas/SeverityType'
        SvcProviderName:
          maxLength: 1024
          type: string
          description: |-
            Name of a service provider. Possible values are:
              -  Cleartouch
              -  DNA
              -  Precision
              -  Premier
              -  Signature
        ServerStatusCode:
          maxLength: 20
          type: string
          description: Server status code of the service provider's application.
        ServerStatusDesc:
          maxLength: 255
          type: string
          description: Description of the server status code of the service provider's application.
        OvrdExceptionInd:
          type: boolean
          description: Value to indicate whether the exception can be overridden by resubmitting the request message.
        SubjectRole:
          type: string
          description: Authorization level required to override, such as Teller and Supervisor.
        SubjectElement:
          type: array
          description: Information about the elements that caused the status.
          items:
            $ref: '#/components/schemas/SubjectElementType'
        ContentHTML:
          type: string
          description: Response status in HTML format. This parameter returns only in some cases.
        AdditionalStatus:
          type: array
          description: Details of the additional status of the response message. This aggregate can appear once for each additional status that the server is expected to provide.
          items:
            $ref: '#/components/schemas/AdditionalStatusType'
      description: Details of the API response messages.
    SeverityType:
      title: SeverityType
      type: string
      description: Severity type of the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section for more information.
      enum:
        - Error
        - Warning
        - Info
    SubjectElementType:
      title: SubjectElementType
      type: object
      properties:
        Path:
          type: string
          description: Path of the element (in XPath absolute notation format) where the error occurred.  If the error occurred at the top-level element, then name of the element is returned in the response.
        ServerPath:
          maxLength: 256
          type: string
          description: Server Path is the Service Provider’s identification of the field in their schema, such as an XPath, field ID, or field name that is associated with the ServerStatusCode. If this element is set, it must be returned in the ServerPath element of the OvrdExceptionData aggregate if the exception is being overridden.
        Value:
          maxLength: 256
          type: string
          description: Human readable information of the EFX data value of the element to be overridden. This value should not be provided for the fields that cannot be represented as a string, for example, binary data.
      description: Information about the subject element
    AdditionalStatusType:
      title: AdditionalStatusType
      type: object
      properties:
        StatusCode:
          maxLength: 20
          type: string
          description: EFX Standard Status code that indicates the result of API response. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section to view the list of all possible status codes.
        StatusDesc:
          maxLength: 255
          type: string
          description: Brief information about the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> for more information.
        Severity:
          $ref: '#/components/schemas/SeverityType'
        SvcProviderName:
          maxLength: 1024
          type: string
          description: |-
            Name of a service provider. Possible values are:
              - Cleartouch
              - DNA
              - Precision
              - Premier
              - Signature
        ServerStatusCode:
          maxLength: 20
          type: string
          description: "Server status code of the service provider's application.  "
        ServerStatusDesc:
          maxLength: 255
          type: string
          description: Description of the server status code of the service provider's application.
        OvrdExceptionInd:
          type: boolean
          description: Value that indicates whether the exception can be overridden by resubmitting the request message.
        SubjectElement:
          type: array
          description: Information about the elements that caused the status.
          items:
            $ref: '#/components/schemas/SubjectElementType'
    addBeneficiaryResponse:
      required:
        - BeneficiaryStatusRec
      properties:
        Status:
          $ref: '#/components/schemas/StatusType'
        BeneficiaryStatusRec:
          $ref: '#/components/schemas/addBeneficiaryResponse_BeneficiaryStatusRec'
      example:
        Status:
          StatusCode: '0'
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Premier
        BeneficiaryStatusRec:
          BeneficiaryKeys:
            AcctKeys:
              AcctId: '10615'
              AcctType: DDA
            BeneficiaryIdent: '1'
          BeneficiaryStatus:
            BeneficiaryStatusCode: Valid
            EffDt: '2023-06-16T20:04:31.045'
    EFXHeader:
      type: string
      properties:
        OrganizationId:
          maxLength: 36
          type: string
          description: Organization Identifier is a unique identifier that represents the financial institution or holding company.  This identifier does not necessarily match the organization identifier or bank identifier in the backend system. To ensure uniqueness across all institutions in all parts of the world, use the Dun & Bradstreet number.
        TrnId:
          maxLength: 36
          type: string
          description: Transaction UUID (Universal Unique Identifier) of the current message.
        VendorId:
          maxLength: 255
          type: string
          description: Unique vendor identification number provided by Fiserv to identify the vendor.
        Context:
          $ref: '#/components/schemas/Context'
      example: '{ "TrnId": "622182", "OrganizationId": "PRMOrg10", "VendorId": "112233", "Context":{ "Channel": "WEB" } }'
    Context:
      type: object
      properties:
        ClientAppName:
          maxLength: 40
          type: string
          description: Name of the client application that is used to send the service request, such as Architect, Commercial Center and others.
        Channel:
          maxLength: 80
          type: string
          description: Name of the channel used by the client application. * 'Online' * 'Phone'  * 'Branch' * 'EFT'
        TrnIdent:
          maxLength: 36
          type: string
          description: Unique identification value of transaction defined by the client.  Also known as Trace Number or Sequence in some systems. When used by a Network defined transaction,  the value of this identifier is typically set to narrow character of 12.
        ClientDateTime:
          pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?'
          type: string
          description: Client date and time as reported by the client application that is making the service request.
        ClientTerminalSeqNum:
          maxLength: 36
          description: 'Client terminal sequence number. type: string'
        OriginatorType:
          type: integer
          description: "The type of organization that the originator represents. This is usually a coded value representing the industry that the organization operates in. It contains the SIC code. For ISO 8583 (DE18) the element is restricted to narrow character of maximum length of 4.  Originator Type codes that apply to financialinstitutions are:\n  6010 - Financial institution—bank, savings and loan (S and L), or credit union  \n  6011 - Financial institution—ATM \n  6012 - Financial institution—merchandise sale \n  6999 - Financial institution—home banking"
          format: int64
        TerminalIdent:
          maxLength: 36
          type: string
          description: Unique code identifying a terminal at the card acceptor location (such as terminal code or terminal number of ATM). See For ISO 8583 (DE41) the element is restricted to a narrow character with maximum length of 8.
        TerminalAddr1:
          maxLength: 64
          type: string
          description: Terminal address line 1.
        TerminalAddr2:
          maxLength: 64
          type: string
          description: Terminal address line 2.
        TerminalAddr3:
          maxLength: 64
          type: string
          description: Terminal address line 3.
        TerminalAddr4:
          maxLength: 64
          type: string
          description: Terminal address line 4.
        TerminalCity:
          maxLength: 32
          type: string
          description: Terminal city name.
        TerminalCounty:
          maxLength: 32
          type: string
          description: Terminal county name.
        TerminalStateProv:
          maxLength: 32
          type: string
          description: State province value as per ISO 3166-2:US codes where the terminal is located.
        TerminalPostalCode:
          maxLength: 11
          type: string
          description: 'Postal Code where the terminal is located. '
        TerminalCountryCodeSource:
          maxLength: 80
          type: string
          description: |-
            Standard country code format where the terminal is located. Valid values are:
              * 'ISO3166-Numeric'
              * 'ISO3166-Alpha-3'
        TerminalCountryCodeValue:
          maxLength: 20
          type: string
          description: Country code value as per the ISO source code set in the TerminalCountryCodeSource field.
        PhoneType:
          maxLength: 80
          type: string
          description: "Type of a phone. Valid values are: * 'EvePhone' * 'DayPhone' * 'EveFax' * 'DayFax' * 'Home' * 'Work' * 'Mobile' * 'Fax' * 'Pager' * 'Modem' * 'Other'"
        PhoneNum:
          type: string
          description: Phone number.
        PhoneExchange:
          maxLength: 80
          type: string
          description: Phone exchange.
        TerminalOwnerName:
          maxLength: 40
          type: string
          description: Name of the owner or operator of the terminal.  For ISO 8583 (DE43) the element is restricted to C-15.
        SystTraceAuditNum:
          maxLength: 36
          type: string
          description: Number assigned by the transaction originator to assist in identifying a transaction uniquely. The trace number remains unchanged for all messages throughout the life of a transaction. This number is not a terminal receipt number. The originating processor increments the trace number by one for each transaction sent to the switch. For ISO 8583 (DE11) the element is restricted to NC-6
        NetworkIdent:
          maxLength: 80
          type: string
          description: Identifies the interchange network for the transaction. The transaction is applied to the specified network settlement counts and balances. For ISO 8583 (DE62) the element is restricted to NC-6
        NetworkRefIdent:
          maxLength: 36
          type: string
          description: Document reference supplied by the system retaining the original source document and used to assist in locating that document. The acquirer of a transaction assigns this number. The issuer processor must retain it in the event that a chargeback is submitted for the transaction. For ISO 8583 (DE37) the element is restricted to C-12
        AcquirerIdent:
          maxLength: 36
          type: string
          description: Identifier of the acquirer who processes the financial transaction. It is a mandatory element in all authorization and financial messages and does not change throughout the life of a transaction. EPOC considers the acquirer as the terminal owner for reporting purposes. For ISO 8583 (DE32) the element is restricted to C-12
        AcquirerCountryCodeSource:
          maxLength: 80
          type: string
          description: |-
            Standard country code format where the acquirer is located. Valid values are:
              * 'ISO3166-Numeric'
              * 'ISO3166-Alpha-3'
        AcquirerCountryCodeValue:
          maxLength: 20
          type: string
          description: Country code value of Acquirer as per the ISO source code set in the AcquirerCountryCodeSource field.
        MerchNum:
          maxLength: 23
          type: string
          description: Unique identification number of a merchant.  For ISO 8583 (DE42) the element is restricted to C-15
        SettlementDate:
          type: string
          description: Transaction settlement date. Used by ISO 8583 (DE63).
          format: date
        SettlementIdent:
          maxLength: 36
          type: string
          description: Identification of the settlement account in which the transaction will be settled.
        BusinessApplIdent:
          maxLength: 80
          type: string
          description: |-
            Identification of the business application. Valid values are:
              * 'P2P' - Person-to-Person
              * 'C2B' - Consumer-to-Business
              * 'A2A' - Account-to-Account
              * 'B2C' - Business-to-Consumer
              * 'B2B' - Business-to-Business
              * 'G2C' - Government-to-Consumer
              * 'C2G' - Consumer-to-Government
        BranchIdent:
          maxLength: 22
          type: string
          description: Branch identification number.
        TellerIdent:
          maxLength: 80
          type: string
          description: Teller identification number.
        TillIdent:
          maxLength: 80
          type: string
          description: Till identification number.
        AMPMCode:
          type: string
          description: 'Transaction posting code. '
          enum:
            - AM
            - PM
        ReentryType:
          type: string
          description: Type of re-entry.
          enum:
            - Manual
            - Auto
        AdditionalSettings:
          type: object
          description: Contains additional information required to successfully process the transaction. Required By Cleartouch
    delBeneficiarySecuredRequest:
      type: object
      required:
        - BeneficiaryKeys
      properties:
        OvrdAutoAckInd:
          type: boolean
          example: true
        BeneficiaryKeys:
          $ref: '#/components/schemas/delBeneficiarySecuredRequest_BeneficiaryKeys'
    delBeneficiarySecuredResponse:
      required:
        - BeneficiaryStatusRec
      properties:
        Status:
          $ref: '#/components/schemas/StatusType'
        BeneficiaryStatusRec:
          $ref: '#/components/schemas/delBeneficiarySecuredResponse_BeneficiaryStatusRec'
      example:
        Status:
          StatusCode: '0'
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Premier
        BeneficiaryStatusRec:
          BeneficiaryKeys:
            AcctKeys:
              AcctId: '10615'
              AcctType: DDA
            BeneficiaryIdent: '1'
          BeneficiaryStatus:
            BeneficiaryStatusCode: Deleted
            EffDt: '2023-06-16T20:06:55.602'
    getBeneficiaryRequest:
      type: object
      required:
        - BeneficiarySel
      properties:
        BeneficiarySel:
          $ref: '#/components/schemas/getBeneficiaryRequest_BeneficiarySel'
    getBeneficiaryResponse:
      required:
        - BeneficiaryRec
      properties:
        Status:
          $ref: '#/components/schemas/StatusType'
        RecCtrlOut:
          $ref: '#/components/schemas/getBeneficiaryResponse_RecCtrlOut'
        BeneficiaryRec:
          type: array
          description: Details of the beneficiary record returned in the response for the specified search criteria.
          items:
            $ref: '#/components/schemas/getBeneficiaryResponse_BeneficiaryRec'
      example:
        Status:
          StatusCode: '0'
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Premier
        RecCtrlOut:
          SentRecCount: 2
        BeneficiaryRec:
          - BeneficiaryKeys:
              AcctKeys:
                AcctId: '1082998135'
                AcctType: CDA
              PartyKeys:
                PartyId: '3149384'
              BeneficiaryIdent: '1'
            BeneficiaryInfo:
              BeneficiaryData:
                FullName: CAROL Y RAMIREZ
                TaxIdentType: None
                TaxIdent: '0'
                PostAddr:
                  AddrFormatType: Label
                  AddrType: Primary
                BeneficiaryType: PRIMARY
                BeneficiaryPercent: 50
            BeneficiaryStatus:
              BeneficiaryStatusCode: Valid
              EffDt: '2023-12-19T07:03:09.749'
          - BeneficiaryKeys:
              AcctKeys:
                AcctId: '1082998135'
                AcctType: CDA
              PartyKeys:
                PartyId: '3149385'
              BeneficiaryIdent: '2'
            BeneficiaryInfo:
              BeneficiaryData:
                FullName: MARK Z LEWIS
                TaxIdentType: SSN
                TaxIdent: '503123484'
                PostAddr:
                  AddrFormatType: Label
                  AddrType: Primary
                BeneficiaryType: PRIMARY
                BeneficiaryPercent: 50
            BeneficiaryStatus:
              BeneficiaryStatusCode: Valid
              EffDt: '2023-12-19T07:03:09.750'
    modBeneficiaryRequest:
      type: object
      required:
        - BeneficiaryInfo
        - BeneficiaryKeys
      properties:
        OvrdAutoAckInd:
          type: boolean
          example: true
        BeneficiaryKeys:
          $ref: '#/components/schemas/modBeneficiaryRequest_BeneficiaryKeys'
        BeneficiaryInfo:
          type: array
          items:
            $ref: '#/components/schemas/modBeneficiaryRequest_BeneficiaryInfo'
    modBeneficiaryResponse:
      required:
        - BeneficiaryStatusRec
      properties:
        Status:
          $ref: '#/components/schemas/StatusType'
        BeneficiaryStatusRec:
          $ref: '#/components/schemas/modBeneficiaryResponse_BeneficiaryStatusRec'
      example:
        Status:
          StatusCode: '0'
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Premier
        BeneficiaryStatusRec:
          BeneficiaryKeys:
            AcctKeys:
              AcctId: '10615'
              AcctType: DDA
            BeneficiaryIdent: '1'
          BeneficiaryStatus:
            BeneficiaryStatusCode: Valid
            EffDt: '2023-06-16T08:05:13.643'
    addBeneficiaryRequest_BeneficiaryInfo_AcctKeys:
      required:
        - AcctId
      type: object
      properties:
        AcctId:
          maxLength: 36
          type: string
          example: '10615'
          description: |-
            Unique identification number of an account record.



            **Note:** Account identifier to which the beneficiary is associated.



            Max provider length: 15
        AcctType:
          type: string
          description: Type of an account
          enum:
            - DDA
            - SDA
            - CDA
          example: 'DDA'
      description: "Unique information to identify the account record.\n\n\n\n**Note:** *Required*\n\n\n\n\n\n\n\nThis aggregate contains the information against which the beneficiary party is associated. "
    addBeneficiaryRequest_BeneficiaryInfo_BeneficiaryData_PartyKeys:
      type: object
      properties:
        PartyId:
          maxLength: 36
          type: string
          example: '3149362'
          description: |-
            Unique identification number of a party record.



            **Note:** Refers to an existing Party to be added as a beneficiary. The PartyId field must be provided in the request, as it uniquely identifies the party.



            Ensure that the same party ID is not added as a beneficiary for the same account more than once. Service provider does not validate existing beneficiaries or new additions. If a party is added multiple times, the provider accepts the request and applies the change. Therefore, data validation must be performed to prevent duplication.



            The Update Beneficiary service operation can be used to update specific beneficiary records if needed. To remove a beneficiary, use the Delete Beneficiary service operation, which allows a new beneficiary to be added later if required.



            Max provider length: 17
      description: |-
        Unique information to identify a party record.



        **Note:** *Required field*
    addBeneficiaryRequest_BeneficiaryInfo_BeneficiaryData_PostAddr:
      required:
        - AddrType
      type: object
      properties:
        AddressIdent:
          maxLength: 36
          type: string
          example: '2104788'
          description: "Unique identifier of an address record.\n\n\n\n**Note:** *Conditionally Required field*\n\n\n\nRequired if an existing address is to be added as a beneficiary address. \n\n\n\nMax provider length: 17"
      description: |-
        Postal address details of the beneficiary party.







        **Note:** *Required*
    addBeneficiaryRequest_BeneficiaryInfo_BeneficiaryData:
      type: object
      properties:
        PartyKeys:
          $ref: '#/components/schemas/addBeneficiaryRequest_BeneficiaryInfo_BeneficiaryData_PartyKeys'
        PostAddr:
          $ref: '#/components/schemas/addBeneficiaryRequest_BeneficiaryInfo_BeneficiaryData_PostAddr'
        BeneficiaryType:
          type: string
          example: 'Friend'
          description: |-
            Type of relationship between a beneficiary and an accountholder.



            **Note:** Any relevant beneficiary types can be provided in the request. Some of the commonly used beneficiary types can be: minor, estate, trust, spouse, parent, entity, sibling, friend, child and so on.
        BeneficiaryPercent:
          type: number
          example: 50
          description: |-
            Percentage of account balance that is conditionally allocated to the beneficiary.



            **Note:** It is an optional field that can be provided in the request to determine the percentage allocated to the beneficiary party on the account as an account can have multiple beneficiaries.



            Ensure that a party ID is not added as a beneficiary for the same account more than once, as the service provider do not validate existing or new beneficiaries. Provider system does not validate the total percentage allocation to beneficiaries. The net beneficiary percent across all beneficiaries should equal 100, unless otherwise specified. Data validation is required to ensure that the beneficiary percent for each party ID is correct.



            The Update Beneficiary service operation can update information, including beneficiary percent, for a specific beneficiary record if needed. The Delete Beneficiary service operation is available to remove a beneficiary, allowing a new beneficiary to be added later if required.
      description: |-
        Details of beneficiary party.



        **Note:** *Required field*
    addBeneficiaryRequest_BeneficiaryInfo:
      type: object
      properties:
        AcctKeys:
          $ref: '#/components/schemas/addBeneficiaryRequest_BeneficiaryInfo_AcctKeys'
        BeneficiaryData:
          $ref: '#/components/schemas/addBeneficiaryRequest_BeneficiaryInfo_BeneficiaryData'
      description: "Beneficiary details of an account.\n\n\n\n**Note:** This aggregate contains the information of the beneficiary party associated to the account. "
    addBeneficiaryResponse_BeneficiaryStatusRec_BeneficiaryKeys_AcctKeys:
      required:
        - AcctId
      type: object
      properties:
        AcctId:
          maxLength: 36
          type: string
          description: |-
            Unique identification number of an account record.





            **Note:** Account identifier to which the beneficiary party is associated.



            Max provider length: 15
        AcctType:
          type: string
          description: |-
            Type of an account.
          enum:
            - DDA
            - SDA
            - CDA
      description: "Unique information to identify the account record.\n\n\n\n**Note:** This aggregate contains the account details against which the beneficiary party is associated. "
    addBeneficiaryResponse_BeneficiaryStatusRec_BeneficiaryKeys:
      required:
        - AcctKeys
      type: object
      properties:
        AcctKeys:
          $ref: '#/components/schemas/addBeneficiaryResponse_BeneficiaryStatusRec_BeneficiaryKeys_AcctKeys'
        BeneficiaryIdent:
          maxLength: 36
          type: string
          description: |-
            Unique identifier of a beneficiary record.



            **Note:** If there are three beneficiaries associated to an account, then three unique identifiers in core would be present to identify/retrieve/ the individual the /respective beneficiary party details.
      description: Unique information to identify a beneficiary record.
    addBeneficiaryResponse_BeneficiaryStatusRec_BeneficiaryStatus:
      required:
        - BeneficiaryStatusCode
      type: object
      properties:
        BeneficiaryStatusCode:
          type: string
          description: Code that indicates the status of a beneficiary record.
        EffDt:
          pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?'
          type: string
          description: "Effective date and time when the beneficiary status is changed. \n\n\n\nFormat: yyyy-MM-ddTHH:mm:ss.sss\n\n\n\nExample: 2021-01-31T23:59:59.999\n\n\n\n**Note:** This field indicates the last updated date and time of the beneficiary party details in the core system. "
      description: "Status details of the beneficiary record.\n\n\n\n**Note:** This aggregate reflects the status and last updated details of the beneficiary party in the provider system. "
    addBeneficiaryResponse_BeneficiaryStatusRec:
      required:
        - BeneficiaryKeys
        - BeneficiaryStatus
      type: object
      properties:
        BeneficiaryKeys:
          $ref: '#/components/schemas/addBeneficiaryResponse_BeneficiaryStatusRec_BeneficiaryKeys'
        BeneficiaryStatus:
          $ref: '#/components/schemas/addBeneficiaryResponse_BeneficiaryStatusRec_BeneficiaryStatus'
      description: |-
        Details of the beneficiary status record in response to beneficiary add operation.



        **Note:** If the operation is successful then this aggregate is returned with a success status.
    delBeneficiarySecuredRequest_BeneficiaryKeys_AcctKeys:
      required:
        - AcctId
      type: object
      properties:
        AcctId:
          maxLength: 36
          type: string
          example: '10615'
          description: |+
            Unique identification number of an account record.



            **Note:** Max provider length: 15 (for DDA/SDA) and 17 (for CDA)











        AcctType:
          type: string
          example: 'DDA'
          description: |-
            Type of an account
          enum:
            - DDA
            - SDA
            - CDA
      description: Unique information to identify the account record.
    delBeneficiarySecuredRequest_BeneficiaryKeys:
      required:
        - AcctKeys
      type: object
      properties:
        AcctKeys:
          $ref: '#/components/schemas/delBeneficiarySecuredRequest_BeneficiaryKeys_AcctKeys'
        BeneficiaryIdent:
          maxLength: 36
          type: string
          example: '1'
          description: |-
            Unique identifier of a beneficiary record.



            **Note:** Refers to beneficiary addenda record number.
      description: Unique information to identify a beneficiary record.
    delBeneficiarySecuredResponse_BeneficiaryStatusRec_BeneficiaryStatus:
      required:
        - BeneficiaryStatusCode
      type: object
      properties:
        BeneficiaryStatusCode:
          type: string
          description: Code that indicates the status of a beneficiary record.
          enum:
            - Deleted
        EffDt:
          pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?'
          type: string
          description: "Effective date and time when the beneficiary status is changed. \n\n\n\nFormat: yyyy-MM-ddTHH:mm:ss.sss\n\n\n\nExample: 2021-01-31T23:59:59.999"
      description: Status details of the beneficiary record.
    delBeneficiarySecuredResponse_BeneficiaryStatusRec:
      required:
        - BeneficiaryKeys
        - BeneficiaryStatus
      type: object
      properties:
        BeneficiaryKeys:
          $ref: '#/components/schemas/delBeneficiarySecuredRequest_BeneficiaryKeys'
        BeneficiaryStatus:
          $ref: '#/components/schemas/delBeneficiarySecuredResponse_BeneficiaryStatusRec_BeneficiaryStatus'
      description: Details of the beneficiary status record in response to delete operation.
    getBeneficiaryRequest_BeneficiarySel_AcctKeys:
      required:
        - AcctId
      type: object
      properties:
        AcctId:
          maxLength: 36
          type: string
          example: '10615'
          description: |+
            Unique identification number of an account record.



            **Note:** Max provider length: 17



        AcctType:
          type: string
          example: 'DDA'
          description: |-
            Type of an account
          enum:
            - DDA
            - SDA
            - CDA
      description: "Unique information to identify the account record.\n\n\n\n**Note:** This field is used to search for a list of beneficiary records for a specified account. "
    getBeneficiaryRequest_BeneficiarySel:
      type: object
      properties:
        AcctKeys:
          $ref: '#/components/schemas/getBeneficiaryRequest_BeneficiarySel_AcctKeys'
        BeneficiaryIdent:
          type: string
          example: '2'
      description: Selection criteria to retrieve the beneficiary records.
    getBeneficiaryResponse_RecCtrlOut:
      required:
        - SentRecCount
      type: object
      properties:
        SentRecCount:
          type: integer
          description: Total number of records that matched the selection criteria and returned in the response message.
          format: int64
      description: |+
        Information retrieved for the criteria specified in the RecCtrlIn aggregate of the request message.



    getBeneficiaryResponse_BeneficiaryKeys_AcctKeys:
      required:
        - AcctId
      type: object
      properties:
        AcctId:
          maxLength: 36
          type: string
          description: |+
            Unique identification number of an account record.



            **Note:** Max provider length: 15 (for DDA) and 17 (for SDA and CDA)











        AcctType:
          type: string
          description: |-
            Type of an account
          enum:
            - DDA
            - SDA
            - CDA
      description: Unique information to identify the account record.
    getBeneficiaryResponse_BeneficiaryKeys:
      required:
        - AcctKeys
      type: object
      properties:
        AcctKeys:
          $ref: '#/components/schemas/getBeneficiaryResponse_BeneficiaryKeys_AcctKeys'
        BeneficiaryIdent:
          maxLength: 36
          type: string
          description: |-
            Unique identifier of a beneficiary record.



            **Note:** Refers to a beneficiary addenda record number.



            Max provider length: 3
      description: Unique information to identify a beneficiary record.
    getBeneficiaryResponse_BeneficiaryInfo_BeneficiaryData_PartyKeys:
      type: object
      properties:
        PartyId:
          maxLength: 36
          type: string
          description: |-
            Unique identification number of a party record.



            **Note:** Max provider length: 17
      description: Unique information to identify a party record.
    getBeneficiaryResponse_BeneficiaryInfo_BeneficiaryData_PostAddr_CountryCode:
      required:
        - CountryCodeValue
      type: object
      properties:
        CountryCodeSource:
          type: string
          description: Standard format of country code.
          enum:
            - SPCountryCode
        CountryCodeValue:
          type: string
          description: |-
            Country code value as per the country code format set in the CountryCodeSource field.



            **Note:** Max provider length: 2
        CountryCodeValueEnumDesc:
          maxLength: 80
          type: string
          description: Description of the enumeration value in the CountryCodeValue field.
      description: Country code details of the beneficiary.
    getBeneficiaryResponse_BeneficiaryInfo_BeneficiaryData_PostAddr:
      required:
        - AddrType
      type: object
      properties:
        AddressIdent:
          maxLength: 36
          type: string
          description: |-
            Unique identifier of an address record.



            **Note:** Max provider length: 17
        AddrFormatType:
          type: string
          description: Type of address format.
          enum:
            - Label
        Addr1:
          maxLength: 64
          type: string
          description: |-
            Address line 1.



            **Note:** Max provider length: 40
        Addr2:
          maxLength: 64
          type: string
          description: "Address line 2. \n\n\n\nTo enter Addr2, an Addr1 field must be provided.\n\n\n\n**Note:** Max provider length: 40"
        City:
          maxLength: 32
          type: string
          description: |-
            Name of the city
        PostalCode:
          maxLength: 11
          type: string
          description: |-
            Postal code or zip code.



            **Note:** Max provider length: 40
        CountryCode:
          $ref: '#/components/schemas/getBeneficiaryResponse_BeneficiaryInfo_BeneficiaryData_PostAddr_CountryCode'
        AddrType:
          type: string
          description: Type of the address.
          enum:
            - Primary
      description: |+
        Postal address details of the beneficiary party.



    getBeneficiaryResponse_BeneficiaryInfo_BeneficiaryData:
      type: object
      properties:
        PartyKeys:
          $ref: '#/components/schemas/getBeneficiaryResponse_BeneficiaryInfo_BeneficiaryData_PartyKeys'
        FullName:
          maxLength: 96
          type: string
          description: |-
            Full name of beneficiary.



            **Note:** Max provider length: 40
        TaxIdentType:
          type: string
          description: Type of tax identification.
          enum:
            - None
            - SSN
            - Foreign
            - ITIN
            - ATIN
            - EIN
        TaxIdent:
          maxLength: 12
          type: string
          description: "Unique tax identification number. \n\n\n\n**Note:** Max provider length: 9 (for tax ID number) and 22 (for foreign tax ID)\n\n\n\n"
        BirthDt:
          type: string
          description: Date of birth of beneficiary.
          format: date
        PostAddr:
          $ref: '#/components/schemas/getBeneficiaryResponse_BeneficiaryInfo_BeneficiaryData_PostAddr'
        BeneficiaryType:
          type: string
          description: "Type of relationship between a beneficiary and an accountholder.\n\n\n\n**Note:** Refers to how the beneficiary is related to the owner of the account. "
        BeneficiaryPercent:
          type: number
          description: Percentage of account balance that is conditionally allocated to the beneficiary.
      description: Details of beneficiary data.
    getBeneficiaryResponse_BeneficiaryInfo:
      type: object
      properties:
        BeneficiaryData:
          $ref: '#/components/schemas/getBeneficiaryResponse_BeneficiaryInfo_BeneficiaryData'
      description: Beneficiary details of an account.
    getBeneficiaryResponse_BeneficiaryStatus:
      required:
        - BeneficiaryStatusCode
      type: object
      properties:
        BeneficiaryStatusCode:
          type: string
          description: Code that indicates the status of a beneficiary record.
        EffDt:
          pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?'
          type: string
          description: "Effective date and time when the beneficiary status is changed. \n\n\n\nFormat: yyyy-MM-ddTHH:mm:ss.sss\n\n\n\nExample: 2021-01-31T23:59:59.999"
      description: Status details of the beneficiary record.
    getBeneficiaryResponse_BeneficiaryRec:
      required:
        - BeneficiaryInfo
        - BeneficiaryKeys
        - BeneficiaryStatus
      properties:
        BeneficiaryKeys:
          $ref: '#/components/schemas/getBeneficiaryResponse_BeneficiaryKeys'
        BeneficiaryInfo:
          $ref: '#/components/schemas/getBeneficiaryResponse_BeneficiaryInfo'
        BeneficiaryStatus:
          $ref: '#/components/schemas/getBeneficiaryResponse_BeneficiaryStatus'
    modBeneficiaryRequest_BeneficiaryKeys_AcctKeys:
      required:
        - AcctId
      type: object
      properties:
        AcctId:
          maxLength: 36
          type: string
          example: '10615'
          description: |+
            Unique identification number of an account record.











        AcctType:
          type: string
          example: 'DDA'
          description: |-
            Type of an account
          enum:
            - DDA
            - SDA
            - CDA
      description: Unique information to identify the account record.
    modBeneficiaryRequest_BeneficiaryKeys:
      required:
        - AcctKeys
      type: object
      properties:
        AcctKeys:
          $ref: '#/components/schemas/modBeneficiaryRequest_BeneficiaryKeys_AcctKeys'
        BeneficiaryIdent:
          maxLength: 36
          type: string
          example: '1'
          description: |-
            Unique identifier of a beneficiary record.



            **Note:** Refers to beneficiary addenda record number.
      description: |-
        Unique information to identify a beneficiary record.



        **Note:** As per the current provider modification approach, it is expected for the client application to send the final state of the beneficiary record. Absence of data in the request is assumed to be deleted from the system of records.
    modBeneficiaryRequest_BeneficiaryInfo_BeneficiaryData:
      type: object
      properties:
        BeneficiaryType:
          type: string
          example: 'Friend'
          description: Type of relationship between a beneficiary and an accountholder.
        BeneficiaryPercent:
          type: number
          example: 49
          description: Percentage of account balance that is conditionally allocated to the beneficiary.
      description: Information of the beneficiary party.
    modBeneficiaryRequest_BeneficiaryInfo:
      type: object
      properties:
        BeneficiaryData:
          $ref: '#/components/schemas/modBeneficiaryRequest_BeneficiaryInfo_BeneficiaryData'
      description: Beneficiary details of an account.
    modBeneficiaryResponse_BeneficiaryStatusRec_BeneficiaryKeys_AcctKeys:
      required:
        - AcctId
      type: object
      properties:
        AcctId:
          maxLength: 36
          type: string
          description: |+
            Unique identification number of an account record.











        AcctType:
          type: string
          description: |-
            Type of an account
          enum:
            - DDA
            - SDA
            - CDA
      description: Unique information to identify the account record.
    modBeneficiaryResponse_BeneficiaryStatusRec_BeneficiaryKeys:
      required:
        - AcctKeys
      type: object
      properties:
        AcctKeys:
          $ref: '#/components/schemas/modBeneficiaryResponse_BeneficiaryStatusRec_BeneficiaryKeys_AcctKeys'
        BeneficiaryIdent:
          maxLength: 36
          type: string
          description: |-
            Unique identifier of a beneficiary record.



            **Note:** Refers to beneficiary addenda record number.
      description: Unique information to identify a beneficiary record.
    modBeneficiaryResponse_BeneficiaryStatusRec_BeneficiaryStatus:
      required:
        - BeneficiaryStatusCode
      type: object
      properties:
        BeneficiaryStatusCode:
          type: string
          description: Code that indicates the status of a beneficiary record.
          enum:
            - Valid
        EffDt:
          pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?'
          type: string
          description: "Effective date and time when the beneficiary status is changed. \n\n\n\nFormat: yyyy-MM-ddTHH:mm:ss.sss\n\n\n\nExample: 2021-01-31T23:59:59.999"
      description: Status details of the beneficiary record.
    modBeneficiaryResponse_BeneficiaryStatusRec:
      required:
        - BeneficiaryKeys
        - BeneficiaryStatus
      type: object
      properties:
        BeneficiaryKeys:
          $ref: '#/components/schemas/modBeneficiaryResponse_BeneficiaryStatusRec_BeneficiaryKeys'
        BeneficiaryStatus:
          $ref: '#/components/schemas/modBeneficiaryResponse_BeneficiaryStatusRec_BeneficiaryStatus'
      description: Details of the beneficiary status record in response to beneficiary update operation.
  parameters:
    EFXHeader:
      name: EFXHeader
      in: header
      description: EFX Header is a common and required component for all API calls, it contains client-related parameters. Please note that the header parameters should be sent as a JSON object under the EFXHeader parameter.
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/EFXHeader'
